// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZDaJnOei3FF8NBhCn0KW-ARvFIxJFvU',
    appId: '1:1022088249975:web:cbc57073674191c59a3c72',
    messagingSenderId: '1022088249975',
    projectId: 'mypospointe',
    authDomain: 'mypospointe.firebaseapp.com',
    storageBucket: 'mypospointe.firebasestorage.app',
    measurementId: 'G-KCZ33MVLW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnnhVaI7nmBQIhVJc1xm58wIei33unwRQ',
    appId: '1:1022088249975:android:c4df38fcf83ce2c79a3c72',
    messagingSenderId: '1022088249975',
    projectId: 'mypospointe',
    storageBucket: 'mypospointe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGKbzy2tJRgOHjaFqykF8KH-4r9P_nNL0',
    appId: '1:1022088249975:ios:766412d074166d729a3c72',
    messagingSenderId: '1022088249975',
    projectId: 'mypospointe',
    storageBucket: 'mypospointe.firebasestorage.app',
    iosBundleId: 'com.example.posPointe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGKbzy2tJRgOHjaFqykF8KH-4r9P_nNL0',
    appId: '1:1022088249975:ios:766412d074166d729a3c72',
    messagingSenderId: '1022088249975',
    projectId: 'mypospointe',
    storageBucket: 'mypospointe.firebasestorage.app',
    iosBundleId: 'com.example.posPointe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvZDaJnOei3FF8NBhCn0KW-ARvFIxJFvU',
    appId: '1:1022088249975:web:e2c93e04e40e98b09a3c72',
    messagingSenderId: '1022088249975',
    projectId: 'mypospointe',
    authDomain: 'mypospointe.firebaseapp.com',
    storageBucket: 'mypospointe.firebasestorage.app',
    measurementId: 'G-GD4FSDYB5H',
  );
}
