// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp8ciEdDIWJEpl4Mln7Y49DBTsPDAuXC4',
    appId: '1:1056308799846:web:170e5ef4740da7126440a7',
    messagingSenderId: '1056308799846',
    projectId: 'pospointe-4d697',
    authDomain: 'pospointe-4d697.firebaseapp.com',
    storageBucket: 'pospointe-4d697.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVuiDta16ph6zJAGZA0CvWHA7gByfYYHM',
    appId: '1:1056308799846:android:3a051f82e3257b3f6440a7',
    messagingSenderId: '1056308799846',
    projectId: 'pospointe-4d697',
    storageBucket: 'pospointe-4d697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPiiKG0GI7LzvK1XpKYQItgtc2CtAM7U',
    appId: '1:1056308799846:ios:73a2078d34106f676440a7',
    messagingSenderId: '1056308799846',
    projectId: 'pospointe-4d697',
    storageBucket: 'pospointe-4d697.firebasestorage.app',
    androidClientId: '1056308799846-bqhud9ljgj871e3jrpiuok96j4p2bdnp.apps.googleusercontent.com',
    iosClientId: '1056308799846-bsv0j7q1a582eggct5pdhlkup3f394qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.posPointe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtPiiKG0GI7LzvK1XpKYQItgtc2CtAM7U',
    appId: '1:1056308799846:ios:73a2078d34106f676440a7',
    messagingSenderId: '1056308799846',
    projectId: 'pospointe-4d697',
    storageBucket: 'pospointe-4d697.firebasestorage.app',
    androidClientId: '1056308799846-bqhud9ljgj871e3jrpiuok96j4p2bdnp.apps.googleusercontent.com',
    iosClientId: '1056308799846-bsv0j7q1a582eggct5pdhlkup3f394qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.posPointe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp8ciEdDIWJEpl4Mln7Y49DBTsPDAuXC4',
    appId: '1:1056308799846:web:7c8e55456c185c866440a7',
    messagingSenderId: '1056308799846',
    projectId: 'pospointe-4d697',
    authDomain: 'pospointe-4d697.firebaseapp.com',
    storageBucket: 'pospointe-4d697.firebasestorage.app',
  );

}